services:
  api:
    build: .
    container_name: urlshortener_api
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql+psycopg://urlshortener:urlshortener@db:5432/urlshortener
      REDIS_URL: redis://redis:6379/0
      # Optional (if you use these in your limiter):
      CREATE_LIMIT: "60"
      CREATE_WINDOW: "60"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: urlshortener_db
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - urlshortener_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: urlshortener_redis
    ports:
      - "6379:6379"

volumes:
  urlshortener_db_data:
